/*
	ESP32_PID.c

	Notes:
	- Adjust pin numbers to match wiring
	- DRV8871: Code currently assumes 3 of these. I think we only have 2 meaning this will need to chang for the H-bridge driver
    - PID constants are configurable for both velocity and position control
	- Add functionality to test one motor at a time
	- Create circuit diagram, stop sending anything and only receive the format Leo requested

	Author: Dom Murphy + Copilot <3
*/

#include <Arduino.h>
#include <math.h>

// Forward-declare Motor so Arduino's autogenerated prototypes (inserted
// before function definitions) can refer to the type when they are created.
struct Motor;

// Compatibility: if building on a non-ESP32 core, ensure IRAM_ATTR is defined
#ifndef IRAM_ATTR
#define IRAM_ATTR
#endif

// Force analog fallback to avoid unresolved ESP32 LEDC symbols during compilation
// on systems where the esp32 core isn't available or isn't selected in the IDE.
// Remove or comment out this line once you've selected an ESP32 board in the IDE
// and the esp32 Arduino core is installed.
#define PWM_FORCE_ANALOG 1

// PWM compatibility wrappers
// On ESP32 we use LEDC (ledcSetup/ledcAttachPin/ledcWrite). On other cores
// provide fallbacks to common Arduino APIs (analogWrite) so the sketch at
// least compiles. For a real ESP32 build make sure you select an ESP32 board
// in the Arduino IDE / PlatformIO so the native LEDC functions are used.
// By default prefer the analogWrite fallback unless we detect the ESP32
// architecture macro. You can force the analog fallback by defining
// `PWM_FORCE_ANALOG` (e.g. add `#define PWM_FORCE_ANALOG 1` before this block).
#if defined(PWM_FORCE_ANALOG)
#define PWM_USE_LEDC 0
#elif defined(ARDUINO_ARCH_ESP32)
#define PWM_USE_LEDC 1
#else
#define PWM_USE_LEDC 0
#endif

static inline void pwmSetup(int channel, int freq, int res) {
#if PWM_USE_LEDC
	ledcSetup(channel, freq, res);
#else
	(void)channel; (void)freq; (void)res;
#endif
}

static inline void pwmAttach(int pin, int channel) {
#if PWM_USE_LEDC
	ledcAttachPin(pin, channel);
#else
	pinMode(pin, OUTPUT);
#endif
}

static inline void pwmWritePin(int pin, int channel, int duty) {
#if PWM_USE_LEDC
	// on ESP32 LEDC, write by channel
	ledcWrite(channel, duty);
#else
	// On AVR/other cores, use analogWrite on the pin. Map duty to 0..255
	// assuming PWM_RESOLUTION <= 8 bits. If resolution is higher, caller
	// should scale accordingly.
	(void)channel;
#if defined(ARDUINO_ARCH_AVR) || defined(ARDUINO_ARCH_SAM) || defined(ARDUINO_ARCH_MEGAAVR)
	analogWrite(pin, duty);
#else
	// Best-effort fallback; many cores provide analogWrite.
	analogWrite(pin, duty);
#endif
#endif
}

// ----------------- Configuration -----------------
// Counts per revolution per channel
#define ENCODER_CPR 64 //Defined in Datasheet, DO NOT CHANGE

// PID update interval (ms)
#define PID_INTERVAL_MS 50

// PWM configuration
#define PWM_FREQ 20000 // 20 kHz
#define PWM_RESOLUTION 8 // bits (0-255)
#define PWM_MAX ((1 << PWM_RESOLUTION) - 1)

// Default Velocity PID gains (shared by all motors). Changeable via serial: "KP <v>", "KI <v>", "KD <v>"
float globalKp = 1.0f;
float globalKi = 0.05f;
float globalKd = 0.01f;

// Default Position controller PID gains (shared). Converts angle error (deg) -> desired output RPM
float posK = 2.0f; 
float posKi = 0.0f; 
float posKd = 0.0f; 
float maxOutputRPM = 2000.0f; // clamp on velocity generated by position controller
float posDeadbandDeg = 1.0f; // small deadband to consider position reached
// Auto position-scaling: when enabled, compute a position P gain that maps
// a configurable angle error (posFullScaleDeg) to the configured maxOutputRPM.
// This means you do not need to hand-tune posK/posKi/posKd — the outer loop
// becomes effectively a P-only mapper to a desired RPM and you can tune the
// velocity PID only (as you requested for demo/overshoot behavior).
bool posAuto = true; // default: auto position scaling ON
float posFullScaleDeg = 90.0f; // angle error (deg) that will request full speed

// Gesture presets: index 0..3 correspond to configurations the hand can take.
// Order: 0=idle, 1=rock, 2=paper, 3=scissors
// Each row: angles (degrees) for motors [m1, m2, m3] measured at the OUTPUT (after gearbox).
// Edit these values to match your mechanical setup.
float gestures[4][3] = {
	{0.0f, 0.0f, 0.0f},    // 0 = idle
	{10.0f, 10.0f, 10.0f}, // 1 = rock (example values)
	{90.0f, 90.0f, 90.0f}, // 2 = paper
	{45.0f, 45.0f, 45.0f}  // 3 = scissors
};

// Convenience names
#define G_IDLE 0
#define G_ROCK 1
#define G_PAPER 2
#define G_SCISSORS 3

// --------------------- Pins & PWM channels -----------------------
// Motor 1
#define M1_IN1 15
#define M1_IN2 2
#define M1_ENC_A 34
#define M1_ENC_B 35

// Motor 2
#define M2_IN1 16
#define M2_IN2 17
#define M2_ENC_A 32
#define M2_ENC_B 33

// Motor 3
#define M3_IN1 18
#define M3_IN2 19
#define M3_ENC_A 25
#define M3_ENC_B 26

// LEDC channels for PWM
#define M1_CH_A 0
#define M1_CH_B 1
#define M2_CH_A 2
#define M2_CH_B 3
#define M3_CH_A 4
#define M3_CH_B 5

// ----------------- Types & Globals -----------------
const int PULSES_PER_REV = ENCODER_CPR * 4; // quadrature

struct Motor {
	// pins
	int in1, in2;
	int encA, encB;
	// ledc channels
	int chA, chB;
	// encoder count (volatile, modified in ISR)
	volatile long count;
	// last read for speed calc
	long lastCount;
	// PID state (velocity PID uses shared gains)
	float integral;
	float lastError;
	float setpoint_rpm; // desired OUTPUT (wheel) RPM
	float setpoint_angle_deg; // desired OUTPUT angle in degrees (NaN when inactive)
	// per-motor position PID state
	float posIntegral; 
	float posLastError; 
	float gearRatio; // gearbox ratio: motor_rev = output_rev * gearRatio
};

// Initialize motors. Values: in1,in2,encA,encB,chA,chB,count,lastCount,integral,lastError,setpoint_rpm,setpoint_angle_deg,gearRatio
// Initialize posIntegral and posLastError to 0
Motor m1 = {M1_IN1, M1_IN2, M1_ENC_A, M1_ENC_B, M1_CH_A, M1_CH_B, 0, 0, 0.0f, 0.0f, 0.0f, NAN, 0.0f, 0.0f, 70.0f};
Motor m2 = {M2_IN1, M2_IN2, M2_ENC_A, M2_ENC_B, M2_CH_A, M2_CH_B, 0, 0, 0.0f, 0.0f, 0.0f, NAN, 0.0f, 0.0f, 70.0f};
// Example: motor3 is 18:1 gearbox in your case — change if needed.
Motor m3 = {M3_IN1, M3_IN2, M3_ENC_A, M3_ENC_B, M3_CH_A, M3_CH_B, 0, 0, 0.0f, 0.0f, 0.0f, NAN, 0.0f, 0.0f, 18.0f};

// Convenience array
Motor* motors[3] = {&m1, &m2, &m3};

// Timing
unsigned long lastPidMs = 0;

// ----------------- Encoder ISRs -----------------
// Simple quadrature: on any change in A or B, increment or decrement
// depending on the current state of A and B.
void IRAM_ATTR encoderISR_m1() {
	bool A = digitalRead(m1.encA);
	bool B = digitalRead(m1.encB);
	if (A == B) m1.count++;
	else m1.count--;
}

void IRAM_ATTR encoderISR_m2() {
	bool A = digitalRead(m2.encA);
	bool B = digitalRead(m2.encB);
	if (A == B) m2.count++;
	else m2.count--;
}

void IRAM_ATTR encoderISR_m3() {
	bool A = digitalRead(m3.encA);
	bool B = digitalRead(m3.encB);
	if (A == B) m3.count++;
	else m3.count--;
}

// ----------------- Motor output helper -----------------
// Apply signed pwm (-PWM_MAX .. PWM_MAX). Positive -> forward
void applyMotorOutput(Motor &m, int signedDuty) {
	if (signedDuty == 0) {
		// brake/coast: write 0 to both
		pwmWritePin(m.in1, m.chA, 0);
		pwmWritePin(m.in2, m.chB, 0);
		return;
	}

	int duty = abs(signedDuty);
	if (duty > PWM_MAX) duty = PWM_MAX;

	if (signedDuty > 0) {
		// forward: PWM on IN1 (chA), IN2 = 0
		pwmWritePin(m.in1, m.chA, duty);
		pwmWritePin(m.in2, m.chB, 0);
	} else {
		// reverse: PWM on IN2 (chB), IN1 = 0
		pwmWritePin(m.in1, m.chA, 0);
		pwmWritePin(m.in2, m.chB, duty);
	}
}

// ----------------- PID update -----------------
void updatePID(Motor &m, unsigned long dt_ms) {
	// read and clear count atomically
	noInterrupts();
	long count = m.count;
	interrupts();

	long delta = count - m.lastCount;
	m.lastCount = count;

	// compute measured motor-shaft RPM (encoder mounted on motor shaft)
	float revs = (float)delta / (float)PULSES_PER_REV;
	float motor_rpm = revs * (60000.0f / (float)dt_ms); // motor shaft RPM

	// compute output (wheel) RPM using gearbox ratio
	float output_rpm = motor_rpm / m.gearRatio;

	// compute total output angle (degrees) for position control
	float motor_revs_total = (float)count / (float)PULSES_PER_REV;
	float output_revs_total = motor_revs_total / m.gearRatio;
	float output_deg_total = output_revs_total * 360.0f;
	float output_deg_mod = fmodf(output_deg_total, 360.0f);
	if (output_deg_mod < 0) output_deg_mod += 360.0f;

	// If a position setpoint is active, compute angle error (shortest path)
	if (!isnan(m.setpoint_angle_deg)) {
		float diff = m.setpoint_angle_deg - output_deg_total; // in degrees
		// normalize to [-180,180]
		while (diff > 180.0f) diff -= 360.0f;
		while (diff <= -180.0f) diff += 360.0f;
		float angle_error = diff;
		// position PID: compute using dt available from the function parameter
		float pos_dt = dt_ms / 1000.0f;
		// If within deadband, consider position reached
		if (fabs(angle_error) <= posDeadbandDeg) {
			m.setpoint_angle_deg = NAN; // deactivate position control
			m.setpoint_rpm = 0.0f;
			m.integral = 0.0f; // reset velocity integral to avoid windup
			m.posIntegral = 0.0f; // reset position integral
			m.posLastError = 0.0f;
		} else {
			// Compute effective position gains. If posAuto is enabled, compute a
			// simple P gain that maps `posFullScaleDeg` -> `maxOutputRPM`. This
			// avoids the need to hand-tune posK/posKi/posKd — the outer loop becomes
			// a proportional mapper to a desired RPM and the velocity PID (which
			// you control) determines dynamics/overshoot.
			float posK_eff = posAuto ? (maxOutputRPM / posFullScaleDeg) : posK;
			float posKi_eff = posAuto ? 0.0f : posKi;
			float posKd_eff = posAuto ? 0.0f : posKd;

			if (!posAuto) {
				m.posIntegral += angle_error * pos_dt;
				// anti-windup for position integral
				float posIntegratorLimit = 10000.0f;
				if (m.posIntegral > posIntegratorLimit) m.posIntegral = posIntegratorLimit;
				if (m.posIntegral < -posIntegratorLimit) m.posIntegral = -posIntegratorLimit;
			} else {
				// ensure integral is zero in auto mode
				m.posIntegral = 0.0f;
			}

			float posDeriv = 0.0f;
			if (pos_dt > 0.0f) posDeriv = (angle_error - m.posLastError) / pos_dt;
			m.posLastError = angle_error;
			float desired_rpm = posK_eff * angle_error + posKi_eff * m.posIntegral + posKd_eff * posDeriv;
			// clamp
			if (desired_rpm > maxOutputRPM) desired_rpm = maxOutputRPM;
			if (desired_rpm < -maxOutputRPM) desired_rpm = -maxOutputRPM;
			m.setpoint_rpm = desired_rpm;
		}
	}

	// PID error is computed on the OUTPUT (wheel) RPM. Serial setpoints are
	// interpreted as desired output RPM.
	float error = m.setpoint_rpm - output_rpm;
	float dt = dt_ms / 1000.0f;
	m.integral += error * dt;
	// anti-windup clamp integral
	float integratorLimit = 1000.0f; // tune as needed
	if (m.integral > integratorLimit) m.integral = integratorLimit;
	if (m.integral < -integratorLimit) m.integral = -integratorLimit;

	float derivative = 0.0f;
	if (dt > 0.0f) derivative = (error - m.lastError) / dt;
	m.lastError = error;

	// PID output (this yields a value; scale/limits map to PWM)
	// use shared/global PID gains
	float out = globalKp * error + globalKi * m.integral + globalKd * derivative;

	// Convert to PWM range (user may need to tune Kp/Ki/Kd so out falls roughly
	// within +/-PWM_MAX). Clip.
	int pwmOut = (int)round(out);
	if (pwmOut > PWM_MAX) pwmOut = PWM_MAX;
	if (pwmOut < -PWM_MAX) pwmOut = -PWM_MAX;

	applyMotorOutput(m, pwmOut);

	// debug printing
}

// Helper to print telemetry for a motor
void printMotorTelemetry(Motor &m, int idx, unsigned long dt_ms) {
	noInterrupts();
	long count = m.count;
	interrupts();
	long delta = count - m.lastCount; // note: lastCount updated in PID; this is instantaneous
	float revs = (float)delta / (float)PULSES_PER_REV;
	float motor_rpm = revs * (60000.0f / (float)dt_ms);
	float output_rpm = motor_rpm / m.gearRatio;

	// compute output angle (degrees) modulo 360
	float motor_revs_total = (float)count / (float)PULSES_PER_REV;
	float output_revs_total = motor_revs_total / m.gearRatio;
	float output_deg_total = output_revs_total * 360.0f;
	float output_deg_mod = fmodf(output_deg_total, 360.0f);
	if (output_deg_mod < 0) output_deg_mod += 360.0f;

	Serial.print("M"); Serial.print(idx); Serial.print(": ");
	Serial.print("set(Out)="); Serial.print(m.setpoint_rpm); 
	if (!isnan(m.setpoint_angle_deg)) {
		Serial.print(" (angle set="); Serial.print(m.setpoint_angle_deg); Serial.print(" deg)");
	}
	Serial.print(", ");
	Serial.print("out_rpm="); Serial.print(output_rpm); Serial.print(", motor_rpm="); Serial.print(motor_rpm);
	Serial.print(", out_angle="); Serial.print(output_deg_mod); Serial.print(" deg");
	Serial.print(", cnt="); Serial.print(count);
	Serial.print(", gear="); Serial.print(m.gearRatio);
	Serial.print(", Kp="); Serial.print(globalKp); Serial.print(" Ki="); Serial.print(globalKi); Serial.print(" Kd="); Serial.println(globalKd);
}

// ----------------- Setup & Loop -----------------
void setup() {
	Serial.begin(115200);
	delay(200);
	Serial.println("ESP32 3-motor PID controller starting...");

	// Configure motors: pins and PWM
	for (int i = 0; i < 3; ++i) {
		Motor &m = *motors[i];
		pinMode(m.in1, OUTPUT);
		pinMode(m.in2, OUTPUT);
		pinMode(m.encA, INPUT_PULLUP);
		pinMode(m.encB, INPUT_PULLUP);
		// attach PWM channels
		pwmSetup(m.chA, PWM_FREQ, PWM_RESOLUTION);
		pwmAttach(m.in1, m.chA);
		pwmSetup(m.chB, PWM_FREQ, PWM_RESOLUTION);
		pwmAttach(m.in2, m.chB);
		// initial outputs 0
		pwmWritePin(m.in1, m.chA, 0);
		pwmWritePin(m.in2, m.chB, 0);
	}

	// Attach encoder interrupts
	attachInterrupt(digitalPinToInterrupt(m1.encA), encoderISR_m1, CHANGE);
	attachInterrupt(digitalPinToInterrupt(m1.encB), encoderISR_m1, CHANGE);
	attachInterrupt(digitalPinToInterrupt(m2.encA), encoderISR_m2, CHANGE);
	attachInterrupt(digitalPinToInterrupt(m2.encB), encoderISR_m2, CHANGE);
	attachInterrupt(digitalPinToInterrupt(m3.encA), encoderISR_m3, CHANGE);
	attachInterrupt(digitalPinToInterrupt(m3.encB), encoderISR_m3, CHANGE);

	lastPidMs = millis();

	Serial.println("Setup complete. Use serial commands: 'M1 <rpm>' to set MOTOR 1 OUTPUT (wheel) RPM setpoint.");
	Serial.println("Example: M1 100  -> set motor 1 output to 100 RPM (telemetry shows motor and output RPM)");
	Serial.println("Commands: KP <v>, KI <v>, KD <v>, POSK <v>, POSI <v>, POSD <v>, VMAX <v>");
	Serial.println("Motor commands: M<n> <rpm>  A<n> <deg>  (e.g. M1 100  A2 90)");
	Serial.println("Gesture commands: send single digit 0..3 to set all motors to a preset,");
	Serial.println(" or 'C<n> <0-3>' to set motor n to a preset. Presets: 0=idle,1=rock,2=paper,3=scissors");
	Serial.println("Position control helpers: POSAUTO <ON|OFF> (auto map angle->RPM), POSFS <deg> (full-scale angle)");

#if PWM_USE_LEDC == 0
	Serial.println("WARNING: PWM running in analogWrite fallback mode. Select an ESP32 board and install the Espressif Arduino core to enable LEDC hardware PWM.");
#endif
}

// Parse simple serial commands
void handleSerial() {
	if (!Serial.available()) return;
	String line = Serial.readStringUntil('\n');
	line.trim();
	if (line.length() == 0) return;

	// Support commands:
	//  - Motor set RPM (output):    M<n> <rpm>
	//  - Set angle (output degrees): A<n> <deg>
	//  - Global PID gains:           KP <v>   KI <v>   KD <v>
	//  - Per-motor PID still not supported; all motors use global gains.

	// Upper-case command token
	String token = line;
	token.toUpperCase();

	if (token.startsWith("KP ")) {
		float v = line.substring(3).toFloat();
		globalKp = v;
		Serial.print("Global Kp="); Serial.println(globalKp);
		return;
	}
	if (token.startsWith("KI ")) {
		float v = line.substring(3).toFloat();
		globalKi = v;
		Serial.print("Global Ki="); Serial.println(globalKi);
		return;
	}
	if (token.startsWith("KD ")) {
		float v = line.substring(3).toFloat();
		globalKd = v;
		Serial.print("Global Kd="); Serial.println(globalKd);
		return;
	}
	if (token.startsWith("POSK ")) {
		float v = line.substring(5).toFloat();
		posK = v;
		Serial.print("Position Kp="); Serial.println(posK);
		return;
	}
	if (token.startsWith("POSAUTO ")) {
		String v = line.substring(8);
		v.trim();
		v.toUpperCase();
		if (v == "ON" || v == "1" || v == "TRUE") posAuto = true;
		else posAuto = false;
		Serial.print("POSAUTO="); Serial.println(posAuto ? "ON" : "OFF");
		return;
	}
	if (token.startsWith("POSFS ")) {
		float v = line.substring(6).toFloat();
		if (v > 0.0f) posFullScaleDeg = v;
		Serial.print("POS full-scale deg="); Serial.println(posFullScaleDeg);
		return;
	}
	if (token.startsWith("POSI ")) {
		float v = line.substring(5).toFloat();
		posKi = v;
		Serial.print("Position Ki="); Serial.println(posKi);
		return;
	}
	if (token.startsWith("POSD ")) {
		float v = line.substring(5).toFloat();
		posKd = v;
		Serial.print("Position Kd="); Serial.println(posKd);
		return;
	}
	if (token.startsWith("VMAX ")) {
		float v = line.substring(5).toFloat();
		maxOutputRPM = v;
		Serial.print("Max output RPM="); Serial.println(maxOutputRPM);
		return;
	}

	// Motor-specific commands (first character indicates command, second character motor index)
	char cmd = line.charAt(0);
	if ((cmd == 'M' || cmd == 'm' || cmd == 'A' || cmd == 'a') && line.length() >= 3) {
		int motorIdx = line.charAt(1) - '1'; // '1'->0
		if (motorIdx < 0 || motorIdx > 2) {
			Serial.println("Invalid motor index. Use 1..3.");
			return;
		}
		int spaceIdx = line.indexOf(' ');
		if (spaceIdx <= 0) {
			Serial.println("No value provided");
			return;
		}
		float val = line.substring(spaceIdx + 1).toFloat();
		Motor &m = *motors[motorIdx];
		if (cmd == 'M' || cmd == 'm') {
			m.setpoint_rpm = val;
			Serial.print("M"); Serial.print(motorIdx+1); Serial.print(" setpoint_rpm(output) "); Serial.println(val);
			return;
		} else if (cmd == 'A' || cmd == 'a') {
			// Angle setpoint (output degrees)
			m.setpoint_angle_deg = val;
			Serial.print("M"); Serial.print(motorIdx+1); Serial.print(" setpoint_angle_deg "); Serial.println(val);
			return;
		}
	}

	// Gesture commands: single digit 0..3 sets all motors, or 'C<n> <0-3>' sets one motor's gesture
	// If the input is a single character digit between '0' and '3', apply gesture to all motors
	if (line.length() == 1 && line.charAt(0) >= '0' && line.charAt(0) <= '3') {
		int g = line.charAt(0) - '0';
		for (int i = 0; i < 3; ++i) {
			Motor &mm = *motors[i];
			mm.setpoint_angle_deg = gestures[g][i];
			mm.setpoint_rpm = 0.0f; // will be set by position PID
			mm.posIntegral = 0.0f;
			mm.posLastError = 0.0f;
			mm.integral = 0.0f;
			mm.lastError = 0.0f;
		}
		Serial.print("Applied gesture "); Serial.println(g);
		return;
	}

	// Per-motor gesture: 'C<n> <0-3>' where n is 1..3
	if ((line.charAt(0) == 'C' || line.charAt(0) == 'c') && line.length() >= 4) {
		int motorIdx = line.charAt(1) - '1';
		if (motorIdx < 0 || motorIdx > 2) { Serial.println("Invalid motor index for C command"); return; }
		int spaceIdx = line.indexOf(' ');
		if (spaceIdx <= 0) { Serial.println("No gesture index provided"); return; }
		int g = line.substring(spaceIdx + 1).toInt();
		if (g < 0 || g > 3) { Serial.println("Gesture must be 0..3"); return; }
		Motor &mm = *motors[motorIdx];
		mm.setpoint_angle_deg = gestures[g][motorIdx];
		mm.setpoint_rpm = 0.0f;
		mm.posIntegral = 0.0f;
		mm.posLastError = 0.0f;
		mm.integral = 0.0f;
		mm.lastError = 0.0f;
		Serial.print("Motor "); Serial.print(motorIdx+1); Serial.print(" set to gesture "); Serial.println(g);
		return;
	}

	Serial.println("Unknown command. Examples: 'M1 100', 'A2 90', 'KP 1.2', 'KI 0.05', 'KD 0.01'");
}

void loop() {
	unsigned long now = millis();
	unsigned long elapsed = now - lastPidMs;
	if (elapsed >= PID_INTERVAL_MS) {
		// Run PID for each motor
		for (int i = 0; i < 3; ++i) {
			updatePID(*motors[i], elapsed);
		}

		// Print telemetry every 1 second
		static unsigned long lastPrint = 0;
		if (now - lastPrint >= 1000) {
			lastPrint = now;
			for (int i = 0; i < 3; ++i) {
				printMotorTelemetry(*motors[i], i+1, 1000);
			}
		}

		lastPidMs = now;
	}

	handleSerial();
}

