alias n='nvim'
alias mains='nvim cm4/src/main.c cm7/src/main.c'
alias layouts='nvim cm4/layout.ld cm7/layout.ld'
alias makey='make flash'
alias m='make OPT=small flash'
alias M='make OPT=fast flash'
alias t='tree -I "build|scripts|dependencies.md|LICENSE|README.md|vendors|compile_commands.json|middlewares" --prune'
alias depend='nvim dependencies.md scripts/dependencies.sh'
alias a='nvim ~/.bash_aliases'
alias A='source ~/.bash_aliases'
alias scripts='nvim scripts/*.sh'
alias startups='nvim cm4/src/startup.c cm7/src/startup.c'
alias utils='nvim common/src/utils.c common/inc/utils.h'
alias uarts='nvim common/src/uart.c common/inc/uart.h'
alias connect='screen /dev/ttyACM0 115200'
